language: node_js
node_js:
  - "8"
install:
  - npm i -g npm@5.8.0
  - npm ci
script:
  - bash travis-verify-build.sh
  - npm run lint
  - npm run test
after_success:
  - npm run coverage
  - npm run coverage-coveralls

